# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Minakian\Documents\PSoC Creator\Bootload\Bootloader.cydsn\Bootloader.cyprj
# Date: Tue, 07 Nov 2017 17:26:26 GMT
#set_units -time ns
create_clock -name {I2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 15 31} [list]


# Component constraints for C:\Users\Minakian\Documents\PSoC Creator\Bootload\Bootloader.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Minakian\Documents\PSoC Creator\Bootload\Bootloader.cydsn\Bootloader.cyprj
# Date: Tue, 07 Nov 2017 17:26:25 GMT
